# Generated by Django 3.0.5 on 2020-10-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200927_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sec_num',
            field=models.IntegerField(default=4497482662),
        ),
    ]
